### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android-scenario-testing#2]
### **Smoke test features**

- [X] Login basic auth correct credentials
- [x] Login OAuth correct credentials (check if driver allows to interact with web browser)  -> check if it is posible to skip fist wizards in emus 
- [X] Login incorrect credentials
- [X] Private share creation -> flaky in emulators. Needs changes in development
- [x] Private share edition 
- [x] Private share deletion
- [X] Public share creation
- [X] Public share edition
- [X] Public share deletion 
- [X] Create folder
- [X] Rename item
- [X] Delete item
- [x] Copy item 
- [x] Move item 
- [x] Available offline file
- [X] Download file
- [x] Sync list of files
- [x] Sync long list of files
- [X] Extra negative tests
 
### Other stuff to do:

- [x] Clean repository (remove maven stuff and some useless skeleton files)
- [X] Add a correct README
- [x] Add guide/howto
- [X] Check if gitignore needs additional entries
- [x] Improve reporting (check other existing libraries or plugins)
- [x] Move all properties to a property file
- [x] Move items to `Given` clauses instead of `Before` 
- [x] Cleaning libraries. Move from local files to gradle dependencies
- [x] Set some logging stuff to track executions.
- [x] Redefine scenarios: include necessary resources in background section (or given)
- [x] Enforce explicit waits

#### Next challenges:

- [ ] OIDC - oCIS [WIP]
- [X] Check if separate authentication tests makes sense  [DONE]
- [x] Automation of test execution
- [x] CI integration!!!!
