### ISSUE TITLE
Roadmap 2.0

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android-scenario-testing#8]
After first round of building/improving tests, these are the new challenges to face:

- [ ] Improve OIDC and browser tests (#4) 
- [ ] Better performance in BitRise -> Moving to DF (genym, saucelabs...)
- [x] Spread the test cases for every scenario (if posible)
- [X] iOS PoC
- [ ] iOS integration
